// MIT License - Copyright (c) 2026 InfraGuard AI Contributors
// InfraGuard AI - Sample Data for Demo

import 'models.dart';

class SampleData {
  SampleData._();

  static final UserProfile demoUser = UserProfile(
    id: 'demo-001',
    name: 'Kwame Asante',
    email: 'kwame@infraguard.gh',
    phone: '+233 24 123 4567',
    role: UserRole.citizen,
    region: 'Greater Accra',
    createdAt: DateTime(2026, 1, 1),
  );

  static final List<Outage> outages = [
    Outage(
      id: 'out-001',
      area: 'Osu, Accra',
      latitude: 5.5560,
      longitude: -0.1819,
      status: OutageStatus.active,
      severity: OutageSeverity.high,
      startTime: DateTime.now().subtract(const Duration(hours: 3)),
      predictedEnd: DateTime.now().add(const Duration(hours: 4)),
      affectedCustomers: 12500,
      cause: 'Transformer overload at Osu substation',
      confidenceScore: 0.87,
    ),
    Outage(
      id: 'out-002',
      area: 'East Legon, Accra',
      latitude: 5.6370,
      longitude: -0.1580,
      status: OutageStatus.predicted,
      severity: OutageSeverity.medium,
      startTime: DateTime.now().add(const Duration(hours: 18)),
      affectedCustomers: 8200,
      cause: 'Heat wave + peak load expected',
      confidenceScore: 0.72,
    ),
    Outage(
      id: 'out-003',
      area: 'Tema Industrial Area',
      latitude: 5.6698,
      longitude: -0.0166,
      status: OutageStatus.resolved,
      severity: OutageSeverity.critical,
      startTime: DateTime.now().subtract(const Duration(days: 1, hours: 5)),
      endTime: DateTime.now().subtract(const Duration(hours: 8)),
      affectedCustomers: 24000,
      cause: 'Cable fault on 33kV feeder',
      confidenceScore: 0.95,
    ),
  ];

  static final List<OutagePrediction> predictions = [
    OutagePrediction(
      id: 'pred-001',
      area: 'Kumasi Central',
      probability: 0.78,
      predictedStart: DateTime.now().add(const Duration(hours: 24)),
      estimatedDuration: const Duration(hours: 6),
      reason: 'Historical pattern + storm forecast',
      contributingFactors: ['Rainy season onset', 'Aging transformer T-045', 'Load spike from Kejetia Market'],
      confidenceScore: 0.82,
    ),
    OutagePrediction(
      id: 'pred-002',
      area: 'Tamale Metropolis',
      probability: 0.62,
      predictedStart: DateTime.now().add(const Duration(hours: 48)),
      estimatedDuration: const Duration(hours: 3),
      reason: 'Harmattan dust affecting insulators',
      contributingFactors: ['Dust accumulation', 'Dry season stress', 'Old connectors'],
      confidenceScore: 0.68,
    ),
    OutagePrediction(
      id: 'pred-003',
      area: 'Cape Coast',
      probability: 0.55,
      predictedStart: DateTime.now().add(const Duration(hours: 72)),
      estimatedDuration: const Duration(hours: 2),
      reason: 'Scheduled maintenance nearby',
      contributingFactors: ['Planned feeder switching', 'University load'],
      confidenceScore: 0.74,
    ),
  ];

  static final List<RoadReport> roadReports = [
    RoadReport(
      id: 'road-001',
      latitude: 5.5913,
      longitude: -0.2229,
      address: 'N1 Highway, Accra-Tema Motorway',
      defectType: DefectType.pothole,
      condition: RoadCondition.poor,
      aiConfidence: 0.94,
      aiAnalysis: 'Large pothole (60cm diameter, 15cm depth). Risk of vehicle damage. Estimated 30 days before critical failure.',
      estimatedRepairCost: 2500.0,
      timeToFailureDays: 30,
      reportedBy: 'Kwame Asante',
      reportedAt: DateTime.now().subtract(const Duration(days: 2)),
      status: 'open',
    ),
    RoadReport(
      id: 'road-002',
      latitude: 6.6885,
      longitude: -1.6244,
      address: 'Kumasi Ring Road, near Adum',
      defectType: DefectType.crack,
      condition: RoadCondition.fair,
      aiConfidence: 0.88,
      aiAnalysis: 'Network cracking detected. Moderate severity. Climate vulnerability: HIGH due to rainfall exposure.',
      estimatedRepairCost: 1200.0,
      timeToFailureDays: 60,
      reportedBy: 'Ama Serwaa',
      reportedAt: DateTime.now().subtract(const Duration(days: 5)),
      status: 'in_progress',
    ),
    RoadReport(
      id: 'road-003',
      latitude: 5.5500,
      longitude: -0.2167,
      address: 'Kaneshie-Mallam Road, Accra',
      defectType: DefectType.flooding,
      condition: RoadCondition.critical,
      aiConfidence: 0.91,
      aiAnalysis: 'Severe waterlogging detected. Road impassable during heavy rain. URGENT: Nearby power infrastructure at risk.',
      estimatedRepairCost: 15000.0,
      timeToFailureDays: 7,
      reportedBy: 'Kofi Mensah',
      reportedAt: DateTime.now().subtract(const Duration(days: 1)),
      status: 'open',
    ),
  ];

  static final List<WorkOrder> workOrders = [
    WorkOrder(
      id: 'wo-001',
      type: WorkOrderType.combined,
      priority: WorkOrderPriority.critical,
      title: 'Kaneshie Road Flood + Power Line Risk',
      description: 'Road flooding on Kaneshie-Mallam Road will damage power line Y-23 in 48 hours. Combined urgency score: 92%',
      location: 'Kaneshie, Accra',
      latitude: 5.5500,
      longitude: -0.2167,
      assignedTeam: 'ECG Response Team + AMA Roads',
      createdAt: DateTime.now().subtract(const Duration(hours: 6)),
      dueDate: DateTime.now().add(const Duration(days: 1)),
      status: 'in_progress',
      urgencyScore: 0.92,
      relatedRoadReportId: 'road-003',
    ),
    WorkOrder(
      id: 'wo-002',
      type: WorkOrderType.electricity,
      priority: WorkOrderPriority.high,
      title: 'Osu Transformer Overhaul',
      description: 'Replace aging transformer at Osu substation. 3 outages in last month traced to this unit.',
      location: 'Osu, Accra',
      latitude: 5.5560,
      longitude: -0.1819,
      assignedTeam: 'ECG Maintenance',
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      dueDate: DateTime.now().add(const Duration(days: 7)),
      status: 'scheduled',
      urgencyScore: 0.78,
      relatedOutageId: 'out-001',
    ),
    WorkOrder(
      id: 'wo-003',
      type: WorkOrderType.roads,
      priority: WorkOrderPriority.medium,
      title: 'N1 Pothole Repair',
      description: 'Large pothole on Accra-Tema Motorway near Tetteh Quarshie. Heavy traffic area.',
      location: 'Accra-Tema Motorway',
      latitude: 5.5913,
      longitude: -0.2229,
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      dueDate: DateTime.now().add(const Duration(days: 14)),
      status: 'open',
      urgencyScore: 0.65,
      relatedRoadReportId: 'road-001',
    ),
  ];

  static final List<InfraAsset> assets = [
    InfraAsset(
      id: 'asset-001',
      type: 'substation',
      name: 'Achimota Substation',
      latitude: 5.6150,
      longitude: -0.2290,
      riskScore: 0.45,
      condition: 'Good',
      lastInspected: DateTime.now().subtract(const Duration(days: 30)),
      forecast7Day: 'Stable – no predicted incidents',
    ),
    InfraAsset(
      id: 'asset-002',
      type: 'transformer',
      name: 'Osu Transformer T-012',
      latitude: 5.5560,
      longitude: -0.1819,
      riskScore: 0.82,
      condition: 'Degraded',
      lastInspected: DateTime.now().subtract(const Duration(days: 90)),
      forecast7Day: 'HIGH RISK – overload likely in 48hrs',
    ),
    InfraAsset(
      id: 'asset-003',
      type: 'road_segment',
      name: 'N1 Highway Seg. 14',
      latitude: 5.5913,
      longitude: -0.2229,
      riskScore: 0.71,
      condition: 'Poor',
      lastInspected: DateTime.now().subtract(const Duration(days: 60)),
      forecast7Day: 'Pothole expansion expected with weekend rains',
    ),
  ];
}
